---
driver:
  name: docker

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[opsworks_cookbook_demo::default]
      - recipe[opsworks_cookbook_demo::install_package]
      - recipe[opsworks_cookbook_demo::add_user]
      - recipe[opsworks_cookbook_demo::create_directory]
      - recipe[opsworks_cookbook_demo::create_files]
      - recipe[opsworks_cookbook_demo::run_command]
      - recipe[opsworks_cookbook_demo::run_script]
      - recipe[opsworks_cookbook_demo::manage_service]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
